# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DJabberd-Plugin-StatusHistory
version:      1.0
version_from: lib/DJabberd/Plugin/StatusHistory.pm
installdirs:  site
requires:
    DateTime:                      0
    DJabberd:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
